apply plugin: 'org.unbroken-dome.test-sets'

testSets {
    integrationTest
}

build.dependsOn integrationTest

dependencies {
    api project(':docker-compose-rule-events-api:docker-compose-rule-events-api-objects')
    implementation 'joda-time:joda-time'
    implementation 'com.github.zafarkhaja:java-semver'
    implementation 'com.google.guava:guava'
    implementation 'commons-io:commons-io'
    implementation 'org.apache.commons:commons-lang3:3.0'
    implementation 'org.awaitility:awaitility'
    implementation 'org.hamcrest:hamcrest'
    implementation 'org.slf4j:slf4j-api'
    implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-yaml'
    implementation 'com.palantir.conjure.java.runtime:conjure-java-jackson-serialization'
    implementation 'one.util:streamex'

    testImplementation 'com.github.stefanbirkner:system-rules'
    testImplementation 'junit:junit'
    testImplementation 'org.assertj:assertj-core'
    testImplementation 'org.slf4j:slf4j-simple'
    testImplementation 'com.github.tomakehurst:wiremock'
    testImplementation 'com.google.guava:guava'
    testImplementation 'org.mockito:mockito-core'


    integrationTestImplementation project.sourceSets.test.output

    testRuntimeOnly 'org.junit.vintage:junit-vintage-engine'
    integrationTestRuntimeOnly 'org.junit.vintage:junit-vintage-engine'
}
