# Excavator auto-updates this file. Please contribute improvements to the central template.

version: 1
merge:
  whitelist:
    labels: ["merge when ready"]
  blacklist:
    labels: ["do not merge"]
  method: squash
  options:
    squash:
      body: pull_request_body
      message_delimiter: ==COMMIT_MSG==
  delete_after_merge: true
update:
  whitelist:
    labels: ["update me"]
