version: "2"

services:
  db:
    image: kiasaki/alpine-postgres
    environment:
      - "POSTGRES_DB=source"
      - "POSTGRES_USER=palantir"
      - "POSTGRES_PASSWORD=palantir"
    ports:
      - "5433"
    network_mode: host
