apply plugin: 'org.unbroken-dome.test-sets'

testSets {
    integrationTest
}

build.dependsOn integrationTest

dependencies {
    api project(':docker-compose-rule-core')
    api 'junit:junit'

    implementation 'joda-time:joda-time'

    testImplementation 'org.hamcrest:hamcrest-core'
    testImplementation 'org.mockito:mockito-core'
    testImplementation 'org.assertj:assertj-core'
    testImplementation 'com.google.guava:guava'

    testRuntimeOnly 'org.junit.vintage:junit-vintage-engine'
    integrationTestRuntimeOnly 'org.junit.vintage:junit-vintage-engine'
}
